// [1]
// BURGER INGREDIENT SECTION

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

// BURGER INGREDIENT WITH SAGA

export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';

// [2]
// ORDER BURGER SECTION

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

// ORDER FETCHING SECTION

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const EMPTY_ORDERS = 'EMPTY_ORDERS';

// ORDER BURGER WITH SAGA

export const PURCHASE_BURGER = 'PURCHASE_BURGER';

// ORDER FETCHING WITH SAGA

export const FETCH_ORDERS = 'FETCH_ORDERS';

// [3]
// AUTHENTICATION SECTION

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';


// AUTHENTICATION WITH SAGA

export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';

// AFTER AUTHENTICATION REDIRECT TO CHECKOUT PAGE

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';



